#!/bin/bash
#

# Please see README.md for a note on fitting and selecting the factor
# models.


TIMESTAMP=$(date +%Y%m%d%H%M%S)

# RANDSEED_SWEEP=$(date +%d%H%M%S)


# DATASEED_SWEEP="1549139415"
# SIMSET_SWEEP="indep"
# FACTOR_SWEEP="linear"
# FACTORK_SWEEP="1"
# ESTCTRL_SWEEP="nctrl oracle Zctrl" 
# FACTORSEED_SWEEP="36127605" 
# RANDSEED_SWEEP="431966185"
# PRIORSP_SWEEP="cauchy"


# DATASEED_SWEEP="1549139415"
# SIMSET_SWEEP="indep"
# FACTOR_SWEEP="linear"
# FACTORK_SWEEP="1"
# ESTCTRL_SWEEP="Actrl " 
# FACTORSEED_SWEEP="771254748" 
# RANDSEED_SWEEP="431966185"
# PRIORSP_SWEEP="cauchy"



# DATASEED_SWEEP="1549139415"
# SIMSET_SWEEP="indep"
# FACTOR_SWEEP="quadratic"
# FACTORK_SWEEP="1"
# ESTCTRL_SWEEP="Zctrl"
# FACTORSEED_SWEEP="771254748" 
# RANDSEED_SWEEP="431966185"
# PRIORSP_SWEEP="cauchy"


# DATASEED_SWEEP="1549139415"
# SIMSET_SWEEP="indep"
# FACTOR_SWEEP="quadratic"
# FACTORK_SWEEP="1"
# ESTCTRL_SWEEP="Actrl"
# FACTORSEED_SWEEP="1549139415" 
# RANDSEED_SWEEP="431966185"
# PRIORSP_SWEEP="cauchy"



# DATASEED_SWEEP="1549139415"
# SIMSET_SWEEP="indep"
# FACTOR_SWEEP="quadratic"
# FACTORK_SWEEP="2"
# ESTCTRL_SWEEP="Zctrl"
# FACTORSEED_SWEEP="659677507" 
# RANDSEED_SWEEP="431966185"
# PRIORSP_SWEEP="cauchy"



# DATASEED_SWEEP="1549139415"
# SIMSET_SWEEP="indep"
# FACTOR_SWEEP="quadratic"
# FACTORK_SWEEP="2"
# ESTCTRL_SWEEP="Actrl"
# FACTORSEED_SWEEP="179267981" 
# RANDSEED_SWEEP="431966185"
# PRIORSP_SWEEP="cauchy"



# DATASEED_SWEEP="1549139415"
# SIMSET_SWEEP="indep"
# FACTOR_SWEEP="quadratic"
# FACTORK_SWEEP="3"
# ESTCTRL_SWEEP="Zctrl"
# FACTORSEED_SWEEP="179267981" 
# RANDSEED_SWEEP="431966185"
# PRIORSP_SWEEP="cauchy"



# DATASEED_SWEEP="1549139415"
# SIMSET_SWEEP="indep"
# FACTOR_SWEEP="quadratic"
# FACTORK_SWEEP="3"
# ESTCTRL_SWEEP="Actrl"
# FACTORSEED_SWEEP="659677507" 
# RANDSEED_SWEEP="431966185"
# PRIORSP_SWEEP="cauchy"


# DATASEED_SWEEP="1549139415"
# SIMSET_SWEEP="indep"
# FACTOR_SWEEP="quadratic"
# FACTORK_SWEEP="1"
# ESTCTRL_SWEEP="Zcovctrl Acovctrl"
# FACTORSEED_SWEEP="771254748" 
# RANDSEED_SWEEP="594924916"
# PRIORSP_SWEEP="horseshoe"



# DATASEED_SWEEP="20133224"
# SIMSET_SWEEP="dep"
# FACTOR_SWEEP="linear"
# FACTORK_SWEEP="1"
# ESTCTRL_SWEEP="nctrl" 
# FACTORSEED_SWEEP="20144133" 
# RANDSEED_SWEEP="22145515"
# PRIORSP_SWEEP="normal"


# DATASEED_SWEEP="20133224"
# SIMSET_SWEEP="dep"
# FACTOR_SWEEP="linear"
# FACTORK_SWEEP="1"
# ESTCTRL_SWEEP="oracle" 
# FACTORSEED_SWEEP="20144133" 
# RANDSEED_SWEEP="21195346"
# PRIORSP_SWEEP="normal"



# DATASEED_SWEEP="20133224"
# SIMSET_SWEEP="dep"
# FACTOR_SWEEP="linear"
# FACTORK_SWEEP="1"
# ESTCTRL_SWEEP="Zctrl" 
# FACTORSEED_SWEEP="20144133" 
# RANDSEED_SWEEP="20235400"
# PRIORSP_SWEEP="normal"



# DATASEED_SWEEP="20133224"
# SIMSET_SWEEP="dep"
# FACTOR_SWEEP="linear"
# FACTORK_SWEEP="1"
# ESTCTRL_SWEEP="Actrl" 
# FACTORSEED_SWEEP="20144133" 
# RANDSEED_SWEEP="20235400"
# PRIORSP_SWEEP="normal"



# DATASEED_SWEEP="20133224"
# SIMSET_SWEEP="dep"
# FACTOR_SWEEP="quadratic"
# FACTORK_SWEEP="1"
# ESTCTRL_SWEEP="Zctrl" 
# FACTORSEED_SWEEP="20144133" 
# RANDSEED_SWEEP="22195956"
# PRIORSP_SWEEP="normal"



# DATASEED_SWEEP="20133224"
# SIMSET_SWEEP="dep"
# FACTOR_SWEEP="quadratic"
# FACTORK_SWEEP="1"
# ESTCTRL_SWEEP="Actrl" 
# FACTORSEED_SWEEP="20144133" 
# RANDSEED_SWEEP="21155118"
# PRIORSP_SWEEP="normal"



# now the causalest.R performs the loop over trials; removed the
# following line 

# TRIAL_SWEEP=$(seq 1 100)

TRIAL_SWEEP="1" 
# PRIORSP_SWEEP="cauchy" # alternatively use normal, horseshoe
ALGO_SWEEP="meanfield"
OUTCOME_SWEEP="linear" 

OUT_SUFFIX=".out"
ROUT_SUFFIX=".Rout"

for DATASEEDi in ${DATASEED_SWEEP}; do
	export DATASEED=${DATASEEDi}
	for SIMSETi in ${SIMSET_SWEEP}; do
		export SIMSET=${SIMSETi}
		for FACTORi in ${FACTOR_SWEEP}; do
			export FACTOR=${FACTORi}
			for FACTORKi in ${FACTORK_SWEEP}; do
				export FACTORK=${FACTORKi}
				for ESTCTRLi in ${ESTCTRL_SWEEP}; do
					export ESTCTRL=${ESTCTRLi}
					for TRIALi in ${TRIAL_SWEEP}; do
						export TRIAL=${TRIALi}
						for FACTORSEEDi in ${FACTORSEED_SWEEP}; do
							export FACTORSEED=${FACTORSEEDi}
							for RANDSEEDi in ${RANDSEED_SWEEP}; do
								export RANDSEED=${RANDSEEDi}
								for ALGOi in ${ALGO_SWEEP}; do
									export ALGO=${ALGOi}
									for PRIORSPi in ${PRIORSP_SWEEP}; do
										export PRIORSP=${PRIORSPi}
										for OUTCOMEi in ${OUTCOME_SWEEP}; do
											export OUTCOME=${OUTCOMEi}
									    	export NAME=causalest_${DATASEEDi}_${SIMSETi}_${FACTORi}_${FACTORKi}_${ESTCTRLi}_${TRIALi}_${FACTORSEEDi}_${RANDSEEDi}_${ALGOi}_${PRIORSPi}_${OUTCOMEi}
									    	export OUTNAME=${NAME}_${TIMESTAMP}${OUT_SUFFIX}
									    	export ROUT=${NAME}_${TIMESTAMP}${ROUT_SUFFIX}
								            echo ${NAME}
								            sbatch --job-name=${NAME} \
								            --output=${OUTNAME} \
								            run_script_causalest_base.sh
								        done
								    done
								done
							done
						done
					done
			    done
			done
		done
	done
done